# Generated by Django 5.2 on 2025-04-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('soil_type', models.CharField(choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loamy', 'Loamy')], max_length=20)),
                ('crop_type', models.CharField(max_length=50)),
                ('planting_date', models.DateField()),
                ('harvesting_date', models.DateField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='farm.farm')),
            ],
        ),
    ]
